/* Product-facing simplification layer. Keeps recovery/debug controls available without making them primary UX. */
(function(){'use strict';
const $=id=>document.getElementById(id);
function text(node){return(node?.textContent||'').replace(/\s+/g,' ').trim()}
function renameButtons(root=document){root.querySelectorAll('button').forEach(b=>{const t=text(b).toLowerCase();if(t==='load audio'||t==='load recording'||t==='load')b.textContent='Play';else if(t==='download'||t==='download audio'||t==='download recording')b.textContent='Export';else if(t==='process'||t==='process recording'||t==='process memory')b.textContent='Create memory';else if(t==='process pending memories')b.textContent='Process now';else if(t==='retry storage')b.textContent='Retry save';else if(t==='recover')b.textContent='Recover audio'});}
function labelCheckbox(id,label){const input=$(id);if(!input)return;const wrap=input.closest('label');if(!wrap)return;for(const n of [...wrap.childNodes])if(n.nodeType===3&&n.textContent.trim())n.textContent=' '+label;}
function simplifySettings(){const form=$('settingsForm');if(!form||$('advancedSettings'))return;labelCheckbox('autoProcessInput','Create memories automatically');labelCheckbox('wakeLockInput','Keep screen awake while listening');labelCheckbox('autoReconnectInput','Reconnect automatically');const appearance=form.querySelector('.appearance-settings');if(appearance&&!$('appearanceAutoHint')){const p=document.createElement('p');p.id='appearanceAutoHint';p.className='settings-help';p.textContent='Auto uses your local time: Light 7 AM–7 PM, Dark 7 PM–7 AM.';appearance.appendChild(p)}const advanced=document.createElement('details');advanced.id='advancedSettings';advanced.className='settings-card product-advanced';advanced.innerHTML='<summary>Advanced & recovery</summary><div class="product-advanced-body"><p>Only needed for troubleshooting, export or manual processing.</p></div>';const body=advanced.querySelector('.product-advanced-body');for(const id of ['retrySaveButton','recoveryButton','runQueueButton','pauseQueueButton']){const el=$(id);if(el)body.appendChild(el)}const processing=$('processing');if(processing)processing.hidden=true;const diagnostics=$('diagnostics');if(diagnostics)form.insertBefore(advanced,diagnostics);else form.appendChild(advanced);renameButtons(form)}
function simplifyLibrary(){renameButtons($('recordingsList')||document);const clear=$('clearRecordingsButton');if(clear){clear.textContent='Manage';clear.title='Remove saved source recordings'}}
function injectStyle(){if($('productUiStyle'))return;const s=document.createElement('style');s.id='productUiStyle';s.textContent='.settings-help{margin:8px 0 0;color:var(--muted);font-size:12px;line-height:1.45}.product-advanced{margin-top:14px!important;padding:0!important;overflow:hidden}.product-advanced>summary{min-height:52px;display:flex;align-items:center;padding:0 14px;font-size:14px;font-weight:700;cursor:pointer}.product-advanced-body{padding:0 14px 14px;display:flex;gap:8px;flex-wrap:wrap}.product-advanced-body p{width:100%;margin:0 0 4px;color:var(--muted);font-size:12px;line-height:1.45}.product-advanced-body button{flex:1;min-width:120px}.recordings-list button{font-size:13px}.recording-card audio{width:100%;margin-top:8px}';document.head.appendChild(s)}
function init(){injectStyle();simplifySettings();simplifyLibrary();const target=$('recordingsList')||document.body;new MutationObserver(()=>simplifyLibrary()).observe(target,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();