/* Apply before first paint; appearance is independent of recording settings. */
(function () {
  'use strict';
  const key='synap-appearance',SHELL_REVISION='1.0.0-prod12',root=document.documentElement,system=window.matchMedia('(prefers-color-scheme: dark)'),valid=value=>['system','light','dark'].includes(value)?value:'system';let preference='system';try{preference=valid(localStorage.getItem(key));}catch(_){}
  function installBrandStyles(){if(document.querySelector('link[data-synap-brand]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='brand.css?v=1.0.0-brain1';link.dataset.synapBrand='brain1';document.head.appendChild(link)}
  function installCompactStyles(){if(document.querySelector('link[data-synap-compact]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='compact.css?v=1.0.0-compact3';link.dataset.synapCompact='compact3';document.head.appendChild(link)}
  function apply(){const mode=preference==='system'?(system.matches?'dark':'light'):preference;root.dataset.theme=mode;root.style.colorScheme=mode;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',mode==='dark'?'#071426':'#f7f9fc');document.querySelectorAll('[data-theme-choice]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.themeChoice===preference)))}
  function addDeferredScript(src,onerror){if(document.querySelector('script[src="'+src+'"]'))return;const script=document.createElement('script');script.src=src;script.defer=true;if(onerror)script.onerror=onerror;document.head.appendChild(script)}
  function installAISettings(){if(typeof document.getElementById!=='function'||typeof document.createElement!=='function')return;const fields=document.querySelector('.processing-fields'),endpoint=document.getElementById('endpointInput'),llmEndpoint=document.getElementById('llmEndpointInput'),token=document.getElementById('tokenInput');if(!fields||!endpoint||!llmEndpoint||!token||document.getElementById('providerInput'))return;const providerField=document.createElement('label');providerField.className='field';providerField.innerHTML='<span>AI provider</span><select id="providerInput"><option value="openai">OpenAI</option><option value="custom">Custom / other provider</option></select><small>OpenAI needs only an API key. Custom mode keeps endpoint support.</small>';const modelFields=document.createElement('div');modelFields.id='openAIModelFields';modelFields.className='processing-fields';modelFields.innerHTML='<label class="field"><span>Transcription model</span><select id="sttModelInput"><option value="gpt-4o-mini-transcribe">GPT-4o mini Transcribe</option><option value="gpt-4o-transcribe">GPT-4o Transcribe</option><option value="gpt-4o-transcribe-diarize">GPT-4o Transcribe Diarize</option></select></label><label class="field"><span>Meeting model</span><select id="llmModelInput"><option value="gpt-5-mini">GPT-5 mini</option><option value="gpt-5">GPT-5</option><option value="gpt-4.1-mini">GPT-4.1 mini</option></select><small>Used for ~5-minute context blocks and the final meeting memory.</small></label><label class="field"><span>Transcription language</span><select id="languageInput"><option value="auto">Auto detect</option><option value="en">English</option><option value="hi">Hindi</option><option value="es">Spanish</option><option value="fr">French</option><option value="de">German</option><option value="ja">Japanese</option></select></label>';const custom=document.createElement('div');custom.id='customEndpointFields';custom.className='processing-fields';custom.append(endpoint.closest('label'),llmEndpoint.closest('label'));const tokenLabel=token.closest('label')?.querySelector('span');if(tokenLabel){tokenLabel.id='apiKeyLabel';tokenLabel.textContent='OpenAI API key'}token.placeholder='sk-…';token.autocomplete='off';fields.prepend(providerField,modelFields,custom);addDeferredScript('ai-providers.js?v=1.0.0-ai2',()=>{const status=document.getElementById('queueStatus');if(status)status.textContent='AI provider module could not load. Reload while online.'});addDeferredScript('recording-bridge.js?v=1.0.0-touch1')}
  function bind(){document.querySelectorAll('[data-theme-choice]').forEach(button=>button.addEventListener('click',()=>{preference=valid(button.dataset.themeChoice);try{localStorage.setItem(key,preference)}catch(_){}apply()}));installAISettings();addDeferredScript('capture-ui.js?v=1.0.0-capture2');apply()}
  installBrandStyles();installCompactStyles();system.addEventListener('change',()=>{if(preference==='system')apply()});window.addEventListener('storage',event=>{if(event.key===key||event.key===null){preference=valid(event.newValue);apply()}});if(typeof navigator!=='undefined'&&navigator.serviceWorker)navigator.serviceWorker.addEventListener('message',event=>{if(event.data?.type==='APP_VERSION'&&(event.data.revision||event.data.version)===SHELL_REVISION){const notice=document.getElementById?.('updateNotice');if(notice&&notice.textContent.includes('App update ready'))notice.hidden=true}});apply();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();